### ISSUE TITLE
Test issue: JOSS-harmonized review templates

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding#49]
### Summary

- [ ] What does this package do? (explain in 50 words or less):

- [ ] Paste the full DESCRIPTION file inside a code block below:

```

```

- [ ] URL for the package (the development repository, not a stylized html page):

- [ ] Who is the target audience?  

- [ ] Are there other R packages that accomplish the same thing? If so, what is different about yours?  

#### Requirements

Confirm each of the following by checking the box.  This package:

- [ ] does not violate the Terms of Service of any service it interacts with. 
- [ ] only exports functions to the NAMESPACE that are intended for end users
- [ ] has a test suite
- [ ] has continuous integration with Travis CI and/or another service  
- [ ] contains a vignette with examples of its essential functions and uses
- [ ] contains a README with instructions for installing the development version. 
- [ ] has a CRAN and OSI accepted license.

#### Publication options

- [ ] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)?
    - [ ] The package contains a [`paper.md`](http://joss.theoj.org/about#paper_structure) with a high-level description.
    - [ ] The package is deposited in a long-term repository with the DOI: 

#### Detail

- [ ] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [ ] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

**Comment by noamross** [comment]
# Editor checks:

- [ ] **Fit**: The package meets or criteria [fit](policies.md#fit) and [overlap](policies.md#fit)
- [ ] **Automated tests:** Package has a testing suite and is tested via Travis-CI or another CI service.
- [ ] **License:** The package has a CRAN accepted license
- [ ] **Repository:** The repository link resolives correctly
- [ ] **Archive** (JOSS only, may be post-review): The repository DOI resolves correctly
- [ ] **Version** (JOSS only, may be post-review): Does the release version given match the GitHub release (v1.0.0)?

---

# Editor comments

---

Reviewers:
Due date:

**Comment by noamross** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- [ ] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

#### Documentation

The package includes all the following forms of documentation:

- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [ ] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [ ] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [ ] **Function Documentation:** for all exported functions in R help
- [ ] **Examples** for all exported functions in R Help that run successfully locally
- [ ] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and `URL`, `Maintainer` and `BugReports` fields in DESCRIPTION 

>##### Paper (for packages co-submitting to JOSS)
>
>The package contains a `paper.md` with:
>
>- [ ] **A short summary** describing the high-level functionality of the software
>- [ ] **Authors:**  A list of authors with their affiliations
>- [ ] **A statement of need** clearly staing problems the software is designed to solve and its target audience.
>- [ ] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Functionality

- [ ] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [ ] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

Estimated hours spent reviewing: 

---

### Review Comments
