### ISSUE TITLE
SAMPLE ISSUE (testing)

### ISSUE THREAD

**Issue by karthik** [ropensci/onboarding#5]
* 1. What does this package do? (explain in 50 words or less)  
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore
* 2. Paste the full DESCRIPTION file inside a code block (bounded by ``` on either end).
```
Package: rglobi
Type: Package
Title: R Interface to Global Biotic Interactions
Description: A programmatic interface to the web service methods
    provided by Global Biotic Interactions (GloBI). GloBI provides 
    access to spatial-temporal species interaction records from 
    sources all over the world. rglobi provides methods to search 
    species interactions by location, interaction type, and 
    taxonomic name. In addition, it supports Cypher, a graph query
    language, to allow for executing custom queries on the GloBI 
    aggregate species interaction dataset.
Version: 0.2.6
Date: 2015-03-17
Authors@R: c(person("Jorrit", "Poelen", role = c("aut", "cre"),
    email = "jhpoelen@xs4all.nl"),
    person("Stephen", "Gosnell", role = "aut",
    email = "stephen.gosnell@baruch.cuny.edu"),
    person("Sergey", "Slyusarev", role = "aut",
    email = "cph.lmy@gmail.com"))
URL: https://github.com/ropensci/rglobi
BugReports: https://github.com/ropensci/rglobi/issues
VignetteBuilder: knitr
Depends:
    R (>= 3.0.1)
License: MIT + file LICENSE
Imports:
    rjson (>= 0.2.13), 
    RCurl
Suggests:
    testthat,
    knitr
```
* 3. URL for the package (the development repository, not a stylized html page): https://github.com/ropensci/rglobi
* 4. What data source(s) does it work with (if applicable)? None
* 5. Who is the target audience? Your doge
* 6. Check the box next to each policy below, confirming that you agree. These are mandatory.
* [x] The repository has continuous integration with Travis and/or another service
* [x] The package contains a vignette
* [x] The package contains a complete readme with devtools install instructions
* [x] The package contains unit tests
* 7. Do you agree to follow the [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? These aren't mandatory, but we strongly suggest you follow them. If you disagree with anything, please explain.
* [x] Does the package have a CRAN accepted license?
* [ ] Are there any packages that your package depends on that are not on CRAN?
* [x] Do you intend for this package to go on CRAN?
* 8. Please add explanations below for any exceptions to the above:

Nothing further to add. Thanks for considering!

**Comment by karthik** [comment]
@sckott @richfitz Take a look and see if the sample above looks ok?

**Comment by sckott** [comment]
looks good to me. I guess we have to add labels, or can the user add a label? if so, would be good to add a label e.g. https://github.com/ropensci/onboarding/labels/package

**Comment by karthik** [comment]
Yeah, Rich already raised that issue.

**Comment by karthik** [comment]
But we could do that too after an initial scan of the 50 word description

**Comment by sckott** [comment]
sounds good

**Comment by jennybc** [comment]
Ask if it passes R CMD check in present state? That will catch/surface lots of things, such as missing function level documentation, right?

**Comment by sckott** [comment]
@jennybc  That makes sense to do - could say don't' submit until no warnings

**Comment by karthik** [comment]
@jennybc Good idea. Should we make this optional? Like _hey I want to get this package to rOpenSci but there is this one pesky warning that won't go away and I don't know how_

I've helped a couple of people that way. OR should we just help where the repo exists and only takes ones passing `CHECK` at this stage of the process.

**Comment by jennybc** [comment]
Proposal: ask submitter to reveal errors, warnings, and/or notes. Don't accept until no errors. At your discretion, help people work through warnings and notes, before or after acceptance.

**Comment by karthik** [comment]
@sckott @jennybc @richfitz  If you all think this looks ok and we've covered the major bases, I think it's time to make this the official route to submit a package to rOpenSci. As Scott might have mentioned, we already have a few packages in the queue that need to get pushed through.

I don't think we have to get everything perfectly ready, just as long as we keep iterating till this looks good (the submission process I imagine will continuously evolve, much like CRAN, although more friendly).

**Comment by sckott** [comment]
Yeah, we have 5 packages (including Rich's) on deck. 

yeah, lets start to point people here to submit

**Comment by karthik** [comment]
:v:

**Comment by karthik** [comment]
I suppose we should revserse the order of these two questions

Does the package have a CRAN accepted license?
 Do you intend for this package to go on CRAN?

**Comment by jennybc** [comment]
Agree it's time to just do it.

**Comment by karthik** [comment]
OK, I'll work with Scott to get the policies repo up to shape so we can open up a first iteration of that.

**Comment by richfitz** [comment]
Still mostly offline, but this looks really great :car: :sunrise_over_mountains:

**Comment by sckott** [comment]
should we redo @richfitz issue with the new format?  or just sorta move on with #1  as is

**Comment by richfitz** [comment]
I vote for starting again so we can point people at a relatively clean process as an example.

**Comment by karthik** [comment]
![](https://dl.dropboxusercontent.com/u/2223411/gifs/batman_yes.gif)

**Comment by sckott** [comment]
agreed on restarting

**Comment by jennybc** [comment]
:+1:

**Comment by richfitz** [comment]
Done :shipit:
